// seed-data.js
const API_URL = 'http://localhost:3000/placement/top-recruiters';

// 1. YOUR DATASETS
const datasets = [
  {
    "year": "2022",
    "headers": [
      "Sl no",
      "Company Name",
      "On Campus/Pool",
      "Type of Company",
      "Package (LPA)",
      "Grand Total"
    ],
    "rows": [
      ["ORACLE CERNER", "On Campus", "IT", "6–7LPA", "2"],
      ["ACCENTURE", "On Campus", "IT", "3.8LPA", "1"],
      ["CAPGEMINI - ANALYST ROLE", "On Campus", "IT", "4LPA", "28"],
      ["CAPGEMINI - SENIOR ANALYST ROLE", "On Campus", "IT", "7.5LPA", "2"],
      ["ACCESS RESEARCH LABS", "On Campus", "IT", "2.4–3LPA", "6"],
      ["HASHEDIN", "On Campus", "IT", "8LPA", "3"],
      ["INFOSYS (HackWithInfy)", "On Campus", "IT", "5LPA", "1"],
      ["INFOSYS LTD", "On Campus", "IT", "3.6LPA", "13"],
      ["ANTSTACK TECHNOLOGIES PRIVATE LIMITED", "Pool Drive", "IT", "6LPA", "1"],
      ["BEARYS PROPERTIES AND DEVELOPMENTS PVT LTD", "On Campus", "IT", "2.4LPA", "1"],
      ["BLACK BOX CORPORATION", "On Campus", "IT", "4–4.5LPA", "3"],
      ["BOSCH GLOBAL SOFTWARE TECHNOLOGIES PVT LTD", "On Campus", "Core", "5LPA", "1"],
      ["COGNIZANT", "On Campus", "IT", "4/5.4/6.75LPA", "25"],
      ["CERIUM SYSTEMS", "On Campus", "Core", "3.1LPA", "6"],
      ["NAVI TECHNOLOGIES LIMITED", "On Campus", "IT", "23.68LPA", "1"],
      ["JUEGO STUDIOS PVT LTD", "On Campus", "IT", "4LPA", "2"],
      ["CELSTREAM TECHNOLOGIES", "On Campus", "IT", "4.1LPA", "1"],
      ["PENTAGON SPACE PVT LTD", "On Campus", "IT", "3.5LPA", "2"],
      ["PERSISTENT SYSTEMS", "On Campus", "IT", "4.71LPA", "3"],
      ["RINEX TECHNOLOGIES PVT LTD", "On Campus", "IT", "5LPA", "3"],
      ["HEXAWARE TECHNOLOGIES", "On Campus", "IT", "4LPA", "1"],
      ["CGI INFORMATION SYSTEMS", "On Campus", "IT", "3.75LPA", "1"],
      ["INVENGER TECHNOLOGIES", "On Campus", "IT", "4LPA", "4"],
      ["SEMNOX", "On Campus", "IT", "3.8LPA", "4"],
      ["CODECRAFT TECHNOLOGIES PVT LTD", "On Campus", "IT", "3.4LPA", "2"],
      ["KAMBALA SOLUTIONS", "On Campus", "Core", "3LPA", "3"],
      ["COGNITIVE CLOUDS SOFTWARE PVT LTD", "On Campus", "IT", "9LPA", "7"],
      ["L&T TECHNOLOGY SERVICES LIMITED", "On Campus", "IT", "4LPA", "1"],
      ["CRANES VARSITY", "On Campus", "IT", "3.5–9LPA", "3"],
      ["CRONJ", "On Campus", "IT", "5.65LPA", "6"],
      ["CSS CORP", "On Campus", "IT", "3LPA", "14"],
      ["VMWARE", "On Campus", "IT", "10.83LPA", "4"],
      ["DREAMSOFT INNOVATIONS PVT LTD", "On Campus", "IT", "4LPA", "4"],
      ["EKA SOFTWARE SOLUTIONS", "On Campus", "IT", "3.5LPA", "1"],
      ["EVOBI AUTOMATIONS PVT LTD", "Pool Drive", "IT", "4LPA", "3"],
      ["EYGBS (INDIA) PRIVATE LIMITED", "On Campus", "IT", "4.5LPA", "19"],
      ["GAININSIGHTS SOLUTIONS", "On Campus", "IT", "3.5–6LPA", "3"],
      ["GLOBAL LOGIC", "On Campus", "IT", "5.5LPA", "1"],
      ["TESSOLVE SEMICONDUCTOR PVT LTD", "On Campus", "Core", "4LPA", "4"],
      ["INFOMATICS INDIA PVT LTD", "On Campus", "IT", "3.5–4LPA", "5"],
      ["ONETRUST", "On Campus", "IT", "5LPA", "6"],
      ["NOVIGO SOLUTIONS", "On Campus", "IT", "3.6–5LPA", "7"],
      ["RISK CONNECT PVT LTD", "On Campus", "IT", "3.3LPA", "6"],
      ["ROBOSOFT TECHNOLOGIES", "On Campus", "IT", "4.5LPA", "13"],
      ["SASKEN TECHNOLOGIES LTD", "On Campus", "IT", "3.7LPA", "31"],
      ["SIGNDESK", "On Campus", "IT", "3.5–5LPA", "3"],
      ["SKOLAR", "On Campus", "IT", "3–6LPA", "6"],
      ["TECHMAHINDRA LTD", "On Campus", "IT", "3.25LPA", "11"],
      ["TATA CONSULTANCY SERVICES", "On Campus", "IT", "3.36LPA", "24"],
      ["TECHMILL TECHNOLOGIES PVT LTD", "Pool Drive", "IT", "6.5LPA", "8"],
      ["TECHTREE IT SYSTEM PVT LTD", "Off Campus", "IT", "2.5LPA", "3"],
      ["TECNIMONT PVT. LTD", "On Campus", "IT", "5.5LPA", "1"],
      ["TIF LABS", "Off Campus", "IT", "3–4LPA", "1"],
      ["VAULTEDGE SOFTWARE PVT LTD", "Off Campus", "IT", "7LPA", "1"],
      ["WINMAN SOFTWARE INDIA LLP", "On Campus", "IT", "4–5.5LPA", "1"],
      ["WIPRO LTD", "On Campus", "IT", "3.5LPA", "41"],
      ["ZENSAR TECHNOLOGIES", "On Campus", "IT", "4LPA", "7"],
      ["SPECBEE", "On Campus", "IT", "3.7LPA", "1"],
      ["SPURTREE TECHNOLOGIES", "On Campus", "IT", "3.5–4.5LPA", "4"],
      ["MSG GLOBAL SOLUTIONS", "On Campus", "IT", "4.5LPA", "4"],
      ["NAGARRO SOFTWARE PVT. LTD.", "Pool Drive", "IT", "4.5LPA", "2"],
      ["YOKOGAWA TECHNOLOGY", "On Campus", "IT", "4.12LPA", "1"]
    ]
  },
  {
    "year": "2023",
    "headers": [
      "Sl no",
      "Company Name",
      "On Campus/Pool",
      "Type of Company",
      "Package (LPA)",
      "Grand Total"
    ],
    "rows": [
      ["TECHMAHINDRA CERIUM SYSTEMS", "On Campus", "Core", "3.6LPA", "5"],
      ["CAPILLARY TECHNOLOGIES", "On Campus", "IT", "16.5LPA", "1"],
      ["CODEYOUNG", "On Campus", "IT", "7.3LPA", "5"],
      ["CONSLEAGUE CONSULTING LTD", "On Campus", "IT", "6LPA", "2"],
      ["MAPLE LABS SOLUTIONS", "On Campus", "IT", "6.2LPA", "3"],
      ["MU SIGMA", "On Campus", "IT", "5LPA", "7"],
      ["PROXELERA PVT. LTD", "On Campus", "IT", "4-6LPA", "2"],
      ["SAP LABS", "On Campus", "IT", "6.5LPA", "2"],
      ["SASKEN TECHNOLOGIES LTD", "On Campus", "IT", "5LPA", "26"],
      ["STELLIUM CONSULTING INDIA PVT LTD", "Pool Drive", "IT", "4.5LPA", "3"],
      ["MAPTELL GEOSYSTEMS PRIVATE LIMITED", "Pool Drive", "IT", "8LPA", "1"],
      ["CODITAS SOLUTIONS LLP", "Pool Drive", "IT", "6LPA", "1"],
      ["ACCESS RESEARCH LABS", "On Campus", "IT", "3-4LPA", "19"],
      ["RISKONNECT", "On Campus", "IT", "3LPA", "3"],
      ["DREAMSOFT INNOVATIONS", "On Campus", "IT", "3.2LPA", "2"],
      ["7EDGE", "On Campus", "IT", "3LPA", "2"],
      ["TATA CONSULTANCY SERVICES", "On Campus", "IT", "3.5LPA", "19"],
      ["MANGALORE INFOTECH", "On Campus", "IT", "4.5LPA", "3"],
      ["COGNIZANT", "On Campus", "IT", "4-4.25LPA", "39"],
      ["CODECRAFT", "On Campus", "IT", "4-5LPA", "5"],
      ["NOVIGO SOLUTIONS PVT. LTD", "On Campus", "IT", "4-5LPA", "4"],
      ["HEXAWARE", "On Campus", "IT", "4LPA", "9"],
      ["99GAMES", "On Campus", "IT", "6.5LPA", "4"],
      ["ROBOSOFT TECHNOLOGIES", "On Campus", "IT", "4.5LPA", "2"],
      ["NEEBAL TECHNOLOGIES PVT. LTD", "Pool Drive", "Core", "4.5LPA", "1"],
      ["TEKSYSTEMS GLOBAL SERVICES PVT. LTD", "Pool Drive", "IT", "6LPA", "3"],
      ["SPURTREETECH", "On Campus", "IT", "4.5LPA", "14"],
      ["DELOITTE DIGITAL", "Pool Drive", "IT", "4.5–6LPA", "2"],
      ["PACE WISDOM SLOUTIONS", "Pool Drive", "IT", "4.5LPA", "2"],
      ["SEMNOX SOLUTIONS", "On Campus", "IT", "4.2LPA", "1"],
      ["NUMOCITY TECHNOLOGIES", "Pool Drive", "Core", "7LPA", "1"],
      ["DUCOM INSTRUMENTS PVT.LTD", "Pool Drive", "Core", "6–7LPA", "1"],
      ["MRESULT", "On Campus", "IT", "5LPA", "3"],
      ["TECH MAHINDRA", "On Campus", "IT", "2–3.5LPA", "2"],
      ["ULTIMEZ TECHNOLOGY", "On Campus", "IT", "3.6LPA", "2"],
      ["PEOL SOLUTIONS", "Pool Drive", "IT", "3LPA", "3"],
      ["SAMSUNG", "Pool Drive", "IT", "7LPA", "2"],
      ["INVENGER TECHNOLOGIES", "On Campus", "IT", "3–7LPA", "6"],
      ["ALOHA TECHNOLOGY", "On Campus", "IT", "3.2LPA", "1"],
      ["TESSOLVE SEMICONDUCTOR", "On Campus", "Core", "4LPA", "3"],
      ["AVON BUILDING SOLUTIONS PVT LTD", "On Campus", "IT", "3–3.6LPA", "2"],
      ["CRESTAEROSPACE TECHNOLOGIES", "On Campus", "IT", "3–3.2LPA", "8"],
      ["ULTIMEZ TECHNOLOGY", "On Campus", "IT", "3.6LPA", "3"],
      ["SSI PEOPLE", "Pool Drive", "IT", "4.25LPA", "4"],
      ["GLOWTOUCH", "On Campus", "IT", "2.4–3LPA", "1"],
      ["KAMBALA SOLUTIONS PVT LTD.", "Pool Drive", "Core", "3LPA", "4"],
      ["TURINGMINDS.AI", "On Campus", "IT", "3LPA", "18"],
      ["FACE PREP", "On Campus", "IT", "3.06LPA", "2"],
      ["KODNEST TECHNOLOGIES PVT LTD", "On Campus", "IT", "3LPA", "3"],
      ["CREDITNIRVANA", "On Campus", "IT", "6LPA", "4"],
      ["AUTOLIV", "Pool Drive", "IT", "3LPA", "1"],
      ["SONATA", "On Campus", "IT", "4LPA", "3"],
      ["SIGNOFF SEMICONDUCTORS", "On Campus", "Core", "3.5LPA", "3"],
      ["ROYOTA", "Pool Drive", "Core", "2.5LPA", "2"],
      ["FUTURENSE TECHNOLOGIES", "On Campus", "IT", "12.5LPA", "2"],
      ["ZOSH AEROSPACE", "On Campus", "Core", "3LPA", "2"],
      ["MIDDLEBYINDIA", "Pool Drive", "IT", "4.52LPA", "1"],
      ["TAYANA MOBILITY TECHNOLOGIES", "Pool Drive", "IT", "4.5LPA", "2"],
      ["DUCOM AEROSPACE", "On Campus", "IT", "5.5LPA", "1"],
      ["IBM", "On Campus", "IT", "4.5LPA", "1"],
      ["INDO MIM PVT LTD", "Pool Drive", "Core", "3.3LPA", "2"],
      ["SHAHI EXPORTS", "Pool Drive", "IT", "3LPA", "3"],
      ["WINMAN SOFTWARE INDIA LLP", "Pool Drive", "IT", "3–5.5LPA", "1"],
      ["RINEX", "On Campus", "IT", "1.44LPA", "1"],
      ["GLOBAL E SOFTSYS", "Off Campus", "IT", "4LPA", "1"],
      ["KARMIC DESIGN PRIVATE LIMITED", "Pool Drive", "Core", "4LPA", "4"],
      ["LOGIXHEALTH", "On Campus", "IT", "5LPA", "1"],
      ["WÜRTH ELEKTRONIK", "Pool Drive", "IT", "6.75LPA", "2"],
      ["JUNTRAN TECHNOLOGIES (P) LTD", "On Campus", "IT", "3.6LPA", "1"],
      ["ORACLE CERNER HEALTHCARE SOLUTIONS INDIA PRIVATE LIMITED", "Off Campus", "IT", "6.11LPA", "1"],
      ["CODEZYNG", "On Campus", "IT", "1.44LPA", "1"],
      ["CRAFT SILICON PVT LTD", "Off Campus", "IT", "3.3LPA", "1"],
      ["VAYS INFOTECH PVT LTD", "On Campus", "IT", "3.4LPA", "2"],
      ["MANPOWERGROUP SERVICE PVT LTD", "Pool Drive", "IT", "4.8LPA", "2"],
      ["RANDSTAD INDIA PVT LTD", "Pool Drive", "IT", "2.6LPA", "1"],
      ["HEMMERSBATCH INDIA PVT LTD", "Off Campus", "IT", "3LPA", "1"],
      ["ORICON ENTERPRISES LTD", "On Campus", "Core", "3LPA", "1"],
      ["OMNENEST", "On Campus", "Core", "3.5LPA", "1"],
      ["VISHWAYON SOFTWARE PVT LTD", "Pool Drive", "IT", "3LPA", "1"],
      ["UNISOFT GLOBAL SERVICE", "Off Campus", "IT", "1.8LPA", "1"],
      ["ITI LTD", "Off Campus", "IT", "1.8LPA", "1"],
      ["UCAM PVT LTD", "On Campus", "IT", "3LPA", "1"],
      ["ELOI CONSULTING PVT LTD", "On Campus", "IT", "2.75LPA", "1"],
      ["YUCCA SOLUTIONS PVT LTD", "Off Campus", "IT", "3.4LPA", "1"],
      ["NAGARRO", "On Campus", "IT", "4.5–6LPA", "2"],
      ["JUEGO STUDIOS PVT LTD", "On Campus", "IT", "3.5–5.5LPA", "2"],
      ["INFOMATICS", "On Campus", "IT", "3–3.5LPA", "2"],
      ["QUESS CORP", "On Campus", "IT", "3.3LPA", "5"],
      ["TRANE TECHNOLOGIES", "On Campus", "IT", "6LPA", "2"],
      ["LIUGONG INDIA PVT. LTD", "On Campus", "IT", "3LPA", "2"],
      ["XFACTR SOFTWARES", "Pool Drive", "IT", "3.5–4.5LPA", "1"],
      ["LEGION ENERGY", "Pool Drive", "IT", "2.4LPA", "1"],
      ["ONEADVANCED", "On Campus", "IT", "4.5–6LPA", "1"],
      ["TECHNOLOGICS GLOBAL PVT LTD", "On Campus", "IT", "2.5–4LPA", "2"],
      ["SPECBEE", "On Campus", "IT", "3.7LPA", "3"]
    ]
  },
  {
    "year": "2024",
    "headers": [
      "Sl no",
      "Company Name",
      "On Campus/Pool",
      "Type of Company",
      "Package (LPA)",
      "Grand Total"
    ],
    "rows": [
      ["SEMNOX SOLUTIONS PVT LTD", "On Campus", "IT", "4.2LPA", "3"],
      ["MAPLE LABS SOLUTIONS PVT LTD", "On Campus", "IT", "5.5LPA", "6"],
      ["TESSOLVE SEMICONDUCTOR", "On Campus", "Core", "4LPA", "2"],
      ["SAP", "On Campus", "IT", "6.5LPA", "2"],
      ["NOVIGO SOLUTIONS", "On Campus", "IT", "4LPA", "4"],
      ["CODECRAFT", "On Campus", "IT", "4LPA", "2"],
      ["ACCESS RESEARCH LABS", "On Campus", "IT", "3LPA", "14"],
      ["MIRAFRA TECHNOLOGY PRIVATE LIMITED", "On Campus", "Core", "3LPA", "7"],
      ["99GAMES", "On Campus", "IT", "1.2LPA", "1"],
      ["BT e-Serv (India) Private Limited", "Pool Drive", "IT", "5.8LPA", "1"],
      ["PAY MASTER", "Pool Drive", "IT", "3.6LPA", "1"],
      ["ELECTRONIC AUTOMATION PRIVATE LTD", "Pool Drive", "Core", "2.8LPA", "1"],
      ["ANAKIN SKYWALKER", "On Campus", "IT", "6.6LPA", "2"],
      ["RIKTAM TECHNOLOGY", "On Campus", "IT", "5.5LPA", "2"],
      ["EURONEXT SOLUTIONS", "On Campus", "IT", "5.5LPA", "3"],
      ["Trianz", "Pool Drive", "IT", "4.25LPA", "1"],
      ["HP", "Pool Drive", "IT", "8LPA", "2"],
      ["STELLIUM CONSULTING INDIA PVT LTD", "Pool Drive", "IT", "4.5LPA", "1"],
      ["APMOSYS TECHNOLOGIES", "On Campus", "Core", "4-6LPA", "1"],
      ["POLYCAB INDIA LIMITED", "Pool Drive", "Core", "3.6LPA", "1"],
      ["PROXELERA PVT. LTD", "On Campus", "IT", "4LPA", "2"],
      ["MUSIGMA", "On Campus", "IT", "5LPA", "4"],
      ["PERSISTENT", "On Campus", "IT", "3.8LPA", "2"],
      ["ACCENTURE", "On Campus", "IT", "4.5LPA", "12"],
      ["BLUEFLAME LABS", "On Campus", "IT", "4.5LPA", "2"],
      ["INDO MIM PVT LTD", "Pool Drive", "Core", "3.3LPA", "1"],
      ["SUBROS LIMITED", "On Campus", "Core", "2.1LPA", "1"],
      ["CAPILLARY TECHNOLOGIES", "On Campus", "IT", "3.6LPA", "4"],
      ["CAPE ELECTRIC", "Pool Drive", "Core", "4LPA", "4"],
      ["INVENGER TECHNOLOGIES PVT LTD", "On Campus", "IT", "3LPA", "6"],
      ["RISKONNECT", "On Campus", "IT", "4LPA", "6"],
      ["NUMOCITY", "On Campus", "Core", "4.5LPA", "3"],
      ["SASKEN TECHNOLOGIES LTD", "On Campus", "IT", "5LPA", "2"],
      ["SPURGE RENTALS PVT LTD", "Pool Drive", "IT", "2.4LPA", "1"],
      ["OMNENEST TECHNOLOGIES PVT LTD", "Pool Drive", "Core", "3.25LPA", "4"],
      ["AYKAN", "Pool Drive", "IT", "3.5LPA", "1"],
      ["BLOB INFOTECH PRIVATE LIMITED", "Pool Drive", "IT", "8LPA", "1"],
      ["ZEOMEGA INFOTECH PRIVATE LTD", "Pool Drive", "IT", "3LPA", "1"],
      ["ACCOLADE TECH SOLUTIONS PRIVATE LIMITED", "Pool Drive", "IT", "2.76LPA", "1"],
      ["KARMIC DESIGN PRIVATE LIMITED", "Pool Drive", "Core", "3LPA", "3"],
      ["SIEMENS", "Pool Drive", "IT", "1.8LPA", "1"],
      ["WESTTEK ENTERPRISES PRIVATE LIMITED", "Pool Drive", "IT", "2.4LPA", "1"],
      ["SIMPLIFY360", "Pool Drive", "IT", "3.5LPA", "1"],
      ["WINMAN SOFTWARE INDIA LLP", "On Campus", "IT", "4.5LPA", "4"],
      ["REXNORD ELECTRONICS & CONTROLS", "On Campus", "IT", "2LPA", "1"],
      ["NIVEUS SOLUTIONS PVT LTD", "On Campus", "IT", "4LPA", "2"],
      ["75F", "On Campus", "IT", "1.8LPA", "1"],
      ["ONEADVANCED", "On Campus", "IT", "5.5LPA", "1"],
      ["INNOVATION IMAGING TECHNOLOGIES PVT", "Pool Drive", "IT", "4LPA", "1"],
      ["MANGALA ELECTRICALS", "Pool Drive", "IT", "2.2LPA", "1"],
      ["iOPEX TECHNOLOGIES", "On Campus", "Core", "4LPA", "2"],
      ["BOSCH", "Pool Drive", "Core", "5.5LPA", "1"],
      ["ORBIT RESEARCH ASSOCIATES PVT LTD", "Pool Drive", "IT", "2.6LPA", "1"],
      ["VELANKANI SOFTWARE PVT LTD", "Pool Drive", "IT", "5LPA", "1"],
      ["GLOWTOUCH", "On Campus", "IT", "2.6LPA", "9"],
      ["TCS", "On Campus", "IT", "3.6LPA", "11"],
      ["VRIKSHAM MANAGEMENT", "Pool Drive", "IT", "1.5LPA", "1"],
      ["EGDK INDIA PRIVATE LTD", "On Campus", "IT", "5.9LPA", "2"],
      ["COGNIZANT", "On Campus", "IT", "4LPA", "5"],
      ["RENEWIN TECHNOLOGIES PVT. LTD.", "Pool Drive", "IT", "3LPA", "2"],
      ["SOPHROSYNE SEMICONDUCTOR", "On Campus", "Core", "5.6LPA", "1"],
      ["FOXCONN HON HAI TECHNOLOGY INDIA MEGA DEVELOPMENT PVT LTD", "Pool Drive", "IT", "2.97LPA", "3"],
      ["ALTRUIST TECHNOLOGIES PRIVATE LIMITED", "Pool Drive", "IT", "2.7LPA", "1"],
      ["ADECCO INDIA", "Pool Drive", "IT", "3.96LPA", "1"],
      ["ACUVATE SOFTWARE", "Pool Drive", "IT", "3LPA", "1"],
      ["LCODE TECHNOLOGIES PVT. LTD.", "Pool Drive", "IT", "3.6LPA", "1"],
      ["CAPGEMINI", "Pool Drive", "IT", "4LPA", "5"],
      ["PRASANNA TECHNOLOGIES PRIVATE LIMITED", "Pool Drive", "IT", "2.39LPA", "2"],
      ["HASHEDIN TECHNOLOGIES PRIVATE LIMITED", "On Campus", "IT", "6.3LPA", "1"],
      ["TECHOUTS", "On Campus", "IT", "3-3.5LPA", "2"],
      ["LIUGONG INDIA", "On Campus", "IT", "3.5LPA", "2"],
      ["ROX HI-TECH", "On Campus", "IT", "3.5-5LPA", "2"],
      ["CREATIVE CRAFTERS", "Pool Drive", "IT", "1.8LPA", "1"],
      ["NEXTUP HR CONSULTING PRIVATE LIMITED", "Pool Drive", "IT", "1.2LPA", "1"],
      ["VOLVO GROUP INDIA PRIVATE LIMITED", "Pool Drive", "IT", "2.64LPA", "1"],
      ["SUNLIGHT SPORTS PRIVATE LIMITED", "Pool Drive", "IT", "5LPA", "1"],
      ["TAPPLENT TECHNOLOGIES INDIA PVT. LTD", "Pool Drive", "IT", "2.4LPA", "1"],
      ["WIPRO", "Pool Drive", "IT", "3.5LPA", "1"],
      ["DATA CARE SYSTEMS PVT LTD", "Pool Drive", "IT", "1.8LPA", "1"],
      ["VEGAM.IO", "Pool Drive", "IT", "4.8LPA", "1"],
      ["SOLAREDGE TECHNOLOGIES (INDIA) PRIVATE LIMITED", "Pool Drive", "IT", "4LPA", "1"],
      ["INDIVILLAGE TECH SOLUTIONS LLP", "Pool Drive", "IT", "3LPA", "1"],
      ["ONEORIGIN", "Pool Drive", "IT", "4LPA", "1"],
      ["JMAN DIGITAL SERVICES", "Pool Drive", "IT", "5LPA", "1"],
      ["TECH MAHINDRA", "Pool Drive", "IT", "3.25LPA", "2"],
      ["WHATFIX", "On Campus", "IT", "9LPA", "1"],
      ["SIGNZY TECHNOLOGIES", "On Campus", "IT", "8-10LPA", "1"],
      ["LOVELOCAL", "On Campus", "IT", "6-8LPA", "1"],
      ["DEVIT SERV", "On Campus", "IT", "6-8LPA", "1"],
      ["WILEY EDGE", "On Campus", "IT", "9LPA", "1"],
      ["BROAD INDIA", "On Campus", "Core", "2.4-4LPA", "1"],
      ["EVERI HOLDINGS", "Pool Drive", "IT", "7LPA", "2"],
      ["TOYOTA KIRLOSKAR AUTO PARTS PVT LTD", "Pool Drive", "IT", "6.32LPA", "2"],
      ["AUTO CNC", "On Campus", "Core", "3-4LPA", "6"],
      ["LAMINA GROUP", "On Campus", "Core", "4-5LPA", "4"],
      ["SSI PEOPLE", "Pool Drive", "IT", "4.5LPA", "2"],
      ["ACCOLITE -DIGITAL", "On Campus", "IT", "6LPA", "2"],
      ["INFOMATICS CORP", "On Campus", "IT", "3.5LPA", "5"],
      ["7EDGE", "On Campus", "IT", "3LPA", "11"],
      ["ENTERPRISEMINDS", "On Campus", "Core", "4LPA", "3"]
    ]
  },
  {
    "year": "2025",
    "headers": [
      "Sl no",
      "Company Name",
      "On Campus/Pool",
      "Type of Company",
      "Package (LPA)",
      "Grand Total"
    ],
    "rows": [
      ["INFOSYS", "On Campus", "IT", "9.5LPA", "2"],
      ["INFOSYS", "Pool Drive", "IT", "3.6LPA", "20"],
      ["XORIANT (MAPLELABS)", "On Campus", "IT", "5.5LPA", "3"],
      ["MUSIGMA", "On Campus", "IT", "5LPA", "8"],
      ["ACCESS RESEARCH LABS (SCLERA)", "On Campus", "IT", "6LPA", "2"],
      ["UNICOURT", "On Campus", "IT", "5.5LPA", "1"],
      ["MIRAFRA TECHNOLOGIES", "Pool Drive", "Core", "3-6LPA", "4"],
      ["COGNIZANT", "On Campus", "IT", "4-6.75LPA", "22"],
      ["SASKEN TECHNOLOGIES", "On Campus", "IT", "5LPA", "4"],
      ["KRISHITANTRA", "On Campus", "IT", "3LPA", "3"],
      ["ARTHA WEBLABS", "On Campus", "IT", "1.44-3.0LPA", "1"],
      ["SOPHROSYNE SEMICONDUCTOR PRIVATE LIMITED", "On Campus", "Core", "5.6LPA", "1"],
      ["CODEZYNG PRIVATE LIMITED", "On Campus", "IT", "3PLA", "3"],
      ["INVENGER TECHNOLOGIES", "On Campus", "IT", "3-4.5LPA", "4"],
      ["ACADEMOR EDUTECH", "On Campus", "IT", "4-6LPA", "114"],
      ["AVIOTRON AEROSPACE PRIVATE LIMITED", "On Campus", "IT", "3.6-3.8LPA", "3"],
      ["X-WORKZ", "On Campus", "IT", "Internship", "13"],
      ["YAZAKI INDIA PRIVATE LIMITED", "On Campus", "IT", "1.80-2.04LPA", "2"],
      ["PLANETSPARK", "On Campus", "IT", "6.5-7.2LPA", "3"],
      ["POORNAM INFO VISION PRIVATE LIMITED", "Pool Drive", "IT", "3.28-5.41LPA", "4"],
      ["NOVIGO SOLUTIONS", "On Campus", "IT", "4LPA", "3"],
      ["ZBYTE TECHNOLOGIES", "On Campus", "IT", "3-4LPA", "5"],
      ["ENTERTAINMENT TECHNOLOGISTS", "On Campus", "IT", "4LPA", "7"],
      ["KWANTUMG RESEARCH LABS PVT LTD", "On Campus", "IT", "4-5LPA", "5"],
      ["RIALTO ENTERPRISES PRIVATE LIMITED", "Pool Drive", "IT", "2.28-2.56LPA", "1"],
      ["QUALITYKIOSK TECHNOLOGIES PRIVATE LIMITED", "Pool Drive", "IT", "2.50LPA", "1"],
      ["QUEST GLOBAL", "On Campus", "IT", "3.75LPA", "1"],
      ["TECH MAHINDRA", "Pool Drive", "IT", "3.25LPA - 5.5LPA", "21"],
      ["XFACTR SOFTWARES PRIVATE LIMITED", "Pool Drive", "IT", "3.20- 4.20 LPA", "4"],
      ["SMARTED INNOVATIONS", "On Campus", "IT", "4-6LPA", "2"],
      ["NIVEUS SOLUTIONS", "Pool Drive", "IT", "4LPA", "3"],
      ["D IT SOLUTIONS", "On Campus", "IT", "3-3.7LPA", "5"],
      ["MICROGENESIS TECHSOFT", "On Campus", "IT", "4LPA", "4"],
      ["LCODE TECHNOLOGIES", "Pool Drive", "IT", "4.21LPA", "3"],
      ["GLOWLOGICS SOLUTIONS", "On Campus", "IT", "5.2LPA", "4"],
      ["IBM", "On Campus", "IT", "4.50LPA", "4"],
      ["VERIFONE INDIA TECHNOLOGY", "On Campus", "IT", "6LPA", "5"],
      ["SILICA DESIGN", "On Campus", "Core", "3LPA", "2"],
      ["WINMAN SOFTWARE INDIA LLP", "Pool Drive", "IT", "4LPA", "2"],
      ["EGDK INDIA PVT. LTD.", "Pool Drive", "IT", "5.9LPA", "4"],
      ["IBM TECHNOLOGY EXPERT LABS", "Pool Drive", "IT", "6.5LPA", "1"],
      ["TECHNOLOGICS GLOBAL", "On Campus", "IT", "4LPA", "2"],
      ["TEKSYSTEMS", "On Campus", "IT", "6LPA", "3"],
      ["LIGHT MECHANICS PVT LTD", "On Campus", "Core", "3.5LPA", "2"],
      ["FACE Prep", "Pool Drive", "IT", "3LPA", "2"],
      ["EFFINIUM CONSULTING INDIA PVT", "Pool Drive", "IT", "4LPA", "2"],
      ["KAKUNJE SOFTWARE PVT", "Pool Drive", "Core", "3.5-4LPA", "2"],
      ["TATA ADVANCED SYSTEMS LTD", "Pool Drive", "IT", "4-5LPA", "6"],
      ["DESIGN WEB TECH", "Pool Drive", "IT", "3-4LPA", "1"],
      ["NEXA INNOV", "On Campus", "IT", "Internship", "12"],
      ["MOVATE", "Pool Drive", "IT", "3.3LPA", "1"],
      ["PRICEEASY AI", "Pool Drive", "IT", "4LPA", "1"],
      ["KVP BUSINESS SOLUTIONS MANGALORE", "Pool Drive", "IT", "3LPA", "1"],
      ["ISIRI TECHNOLOGIES PVT.LTD", "Pool Drive", "IT", "4LPA", "1"],
      ["BROADRIDGE FINANCIAL SOLUTIONS", "Pool Drive", "IT", "3-4LPA", "1"],
      ["ABHIMO TECHNOLOGIES PVT LDT", "On Campus", "IT", "3LPA", "4"],
      ["ACCOLADE TECHSOLUTION", "Pool Drive", "IT", "3LPA", "2"],
      ["TINY PRISM LABS", "On Campus", "IT", "Internship", "1"],
      ["RUDDER ANALYTICS", "On Campus", "IT", "4.8LPA", "1"],
      ["SOLAREDGE", "Pool Drive", "Core", "4LPA", "4"],
      ["AQUERALABS INDIA", "On Campus", "IT", "5.6LPA", "3"],
      ["KRUTANIC SOLUTIONS", "Pool Drive", "IT", "6LPA", "48"],
      ["INFOMATICS CORP", "On Campus", "IT", "3-3.5LPA", "1"],
      ["RUDDER ANALYTICS", "On Campus", "IT", "4.8LPA", "2"],
      ["REACHINBOX AI", "On Campus", "IT", "6-8L", "3"],
      ["MANIKARAN POWER LIMITED", "On Campus", "Core", "4.5L", "5"],
      ["VRAIO SOFTWARE SOLUTIONS PVT LTD", "On Campus", "IT", "3-4LPA", "10"],
      ["SAFESEND TECHNOLOGIES", "Pool Drive", "IT", "6LPA", "1"],
      ["JUEGO STUDIOS PVT LTD", "On Campus", "IT", "4.5LPA", "1"],
      ["RISKONNECT", "On Campus", "IT", "3LPA", "5"],
      ["GAININSIGHTS SOLUTIONS", "On Campus", "IT", "3.2LPA", "2"],
      ["ICALTECH INNOVATIONS PVT LTD", "On Campus", "Core", "3.25LPA", "2"],
      ["RITZ7 AUTOMATIONS PRIVATE LIMITED", "Pool Drive", "IT", "2.88LPA", "1"],
      ["YUCCA IT SOLUTIONS PVT LTD", "Pool Drive", "IT", "3LPA", "1"],
      ["CAPGEMINI", "On Campus", "IT", "4LPA", "2"],
      ["EXELON CIRCUITS PRIVATE LIMITED", "On Campus", "IT", "1.8LPA", "2"],
      ["WARPDRIVE", "On Campus", "IT", "1.14LPA", "1"],
      ["ACCOLADE TECH SOLUTIONS PRIVATE LIMITED", "Pool Drive", "IT", "3LPA", "1"],
      ["MARRIAN INFRA PVT LTD", "Pool Drive", "IT", "1.8LPA", "1"],
      ["UPDAPT - ESG TECH", "On Campus", "IT", "3LPA", "2"],
      ["KARMIC", "Pool Drive", "Core", "3LPA", "1"],
      ["Neya AI Pvt Ltd!", "Pool Drive", "IT", "3LPA", "2"],
      ["EGDK", "Pool Drive", "IT", "5.9LPA", "1"]
    ]
  }
];

// 2. MAIN SEEDING FUNCTION
async function seedData() {
  console.log('🚀 Starting seed process (Bottom to Top)...');
  
  let successCount = 0;
  let errorCount = 0;

  for (const dataset of datasets) {
    console.log(`\n📂 Processing year: ${dataset.year}`);
    
    // ---------------------------------------------------------
    // CHANGE 1: REVERSE ORDER (Bottom to Top)
    // ---------------------------------------------------------
    const reversedRows = [...dataset.rows].reverse();

    for (const row of reversedRows) {
      // Data format in row: ["Company", "Mode", "Type", "Package", "Count"]
      
      const payload = {
        companyName: row[0],
        mode: row[1],
        type: row[2],
        package: row[3],
        count: parseInt(row[4]),
        
        // ---------------------------------------------------------
        // CHANGE 2: SAFETY FIX (Convert Year to Number)
        // Many backends crash if "year" is a string "2022" instead of number 2022
        // ---------------------------------------------------------
        year: parseInt(dataset.year) 
      };

      try {
        const response = await fetch(API_URL, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(payload),
        });

        if (response.ok) {
          process.stdout.write('.'); // Print dot for success
          successCount++;
        } else {
          // ---------------------------------------------------------
          // CHANGE 3: BETTER ERROR LOGGING
          // ---------------------------------------------------------
          const errText = await response.text();
          console.error(`\n❌ Failed: ${payload.companyName} | Status: ${response.status}`);
          console.error(`   Server Response: ${errText}`);
          errorCount++;
        }
      } catch (error) {
        console.error(`\n❌ Network/Code Error: ${payload.companyName}`, error.message);
        errorCount++;
      }
    }
  }

  console.log(`\n\n✅ Seeding Complete!`);
  console.log(`Successful: ${successCount}`);
  console.log(`Failed: ${errorCount}`);
}

// 3. EXECUTE
seedData();